name: "PyLint"

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: "Checkout Repository - PR"
        uses: actions/checkout@v3
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      -
        name: "Checkout Repository - PUSH"
        uses: actions/checkout@v3
        if: github.event_name != 'pull_request'
      -
        name: "Setup python"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
      -
        name: "Setup installation requirements"
        run: |
          pip install --upgrade pip
          pip install wheel pylint
          pip install -r requirements.txt
        shell: bash
      -
        name: "Lint package(s)"
        run: |
          pkgs_pth=$(python3 -c 'import re; print(" ".join(re.findall("([^\s]+)", ${{ toJSON(inputs.lint-path) }})))')
          pylint --exit-zero --output-format=text:pylint_score.txt,colorized $pkgs_pth
        shell: bash
      -
        name: "Get numeric pylint score and badge color"
        id: parameters-badge
        run: |
          python ${{ github.action_path }}/get_score_color.py \
          ${{ inputs.color-bad-score }} \
          ${{ inputs.color-ok-score }} \
          ${{ inputs.color-good-score }} \
          ${{ inputs.color-perfect-score }}
        shell: bash
      -
        # $(echo ${{ inputs.badge-text }} | sed 's/ /%20/g') replaces spaces with %20
        name: "Create badge and substitute it in README.md"
        run: |
          python ${{ github.action_path }}/create_subs_badge.py \
          ${{ inputs.readme-path }} \
          ${{ steps.parameters-badge.outputs.pylint_score }} \
          $(echo ${{ inputs.badge-text }} | sed 's/ /%20/g') \
          ${{ steps.parameters-badge.outputs.badge_color }}
        shell: bash
      -
        name: "Push README with changed badge to origin"
        uses: EndBug/add-and-commit@v9
        with:
          add: 'README.md'
          default_author: github_actions
          message: 'Updated pylint badge'
          push: 'true'